name: CI Build CUSTOM_FD6288_G431

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build CI
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            make arm_sdk_install
            make -j1 CUSTOM_FD6288_G431
          elif [ "$RUNNER_OS" == "Windows" ]; then
            make arm_sdk_install
            tools/windows/make/bin/make -j1 CUSTOM_FD6288_G431
          fi

      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: AM32-binaries-${{ matrix.os }}
          path: obj/AM32_CUSTOM_FD6288_G431_*.hex
          retention-days: 60
          if-no-files-found: error
              
